services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  fastapi:
    build: ./api
    container_name: fastapi
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://root:password@mongodb:27017/
      - MINIO_URL=http://minio:9000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - minio
    volumes:
      - ./api:/app

volumes:
  mongodb_data:
  minio_data: