kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane # master node
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 9001
        hostPort: 9001
        protocol: TCP
    extraMounts:
      - hostPath: /Users/care/kubes-data
        containerPath: /mnt/data
  - role: worker
    extraMounts:
      - hostPath: /Users/care/kubes-data
        containerPath: /mnt/data
  - role: worker
    extraMounts:
      - hostPath: /Users/care/kubes-data
        containerPath: /mnt/data
  - role: worker
    extraMounts:
      - hostPath: /Users/care/kubes-data
        containerPath: /mnt/data
