apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
data:
  MONGO_URL: "mongodb://root:password@mongodb:27017/"
  MINIO_URL: "http://minio:9000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  MINIO_ROOT_USER: "root"
  MINIO_ROOT_PASSWORD: "password"