apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongodb-config
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-data
              mountPath: /data/configdb
              subPath: configdb
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-09-22T00-33-43Z-cpuv1
          imagePullPolicy: IfNotPresent
          args: ["server", "/data", "--console-address", ":9001"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          envFrom:
            - configMapRef:
                name: minio-config
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: alpine:latest
          command: [
              "sh",
              "-c",
              'apk add --no-cache curl netcat-openbsd;
              echo "Waiting for MinIO...";
              until curl -s http://minio:9000 > /dev/null; do
              echo "MinIO not ready yet...";
              sleep 5;
              done;
              echo "MinIO is up";
              echo "Waiting for MongoDB...";
              until nc -z -w2 mongodb 27017; do
              echo "MongoDB not ready yet...";
              sleep 5;
              done;
              echo "MongoDB is up"',
            ]
      containers:
        - name: fastapi
          image: e3tow1c/ipcam-fastapi:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fastapi-config
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
# spec:
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#       - name: frontend
#         image: ipcam-frontend:latest
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 3000
