apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: mongodb-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-config-pvc
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  volumeName: mongodb-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: minio-pv